Install new bin/venv and update Makefile

diff --git a/bin/venv b/bin/venv
--- a/bin/venv
+++ b/bin/venv
@@ -1,85 +1,131 @@
 #!/usr/bin/env bash
+#
+# Initialize a python virtual environment and execute the arguments given.
+# Defaults to Python 3.x.
+#
+# Usage: bin/venv [-h|--help]
+#                 [-i|--intall-path=<path>]
+#                 [-r|--reset]
+#                 [-v|--version=<2|3>]
+#                 --
+#                 <args...>
+#
+#-----------------------------------------------------------------------------
+
+# The list of paths below will be searced and first one found wins unless you override
+# with PYTHON_3_PATH or PYTHON_2_PATH.
+
+PYTHON_3_PATHS="
+/shares/hii/sw/python/3.5.3/bin/python3.5
+/opt/hii/python/3.5.3/bin/python3.5
+/usr/bin/python3.5
+/usr/local/bin/python3.5
+"
+
+PYTHON_2_PATHS="
+/shares/hii/sw/python/2.7.13/bin/python2.7
+/opt/hii/python/2.7.13/bin/python2.7
+/usr/bin/python2.7
+/usr/local/bin/python2.7
+"
+
+usage() {
+  echo "Usage: $(basename $0) [-h|--help] [-i|--install-path=<venv_path] [-r|--reset] [-v|--version=<2|3>] -- <args...>" 1>&2
+  exit 1
+}
+
+err() {
+  echo "$@" 1>&2
+}
+
+cmd() {
+  err
+  echo "cmd>" "$@" | sed -r 's/.{132}/& \n     /g' 1>&2
+  "$@"
+}
+
+get_venv() {
+  local virtualenv_name="$1"
+  local paths="$2"
+  local path
+
+  for path in ${paths}; do
+    if [[ -x $(dirname ${path})/${virtualenv_name} ]]; then
+      echo $(dirname ${path})/${virtualenv_name}
+      return
+    fi
+  done
+  echo "Error: Found no virtualenv binary in the following paths: ${paths}" 1>&2
+  exit 1
+}
+
+run_python() {
+  local version="$1"; shift
+  local paths="$1"; shift
+
+  case ${version} in
+    2) virtualenv_name=virtualenv; python_name=python;;
+    3) virtualenv_name=pyvenv; python_name=python3;;
+  esac
+
+  if [[ -z ${PYTHON_PATH} ]]; then
+    virtualenv=$(get_venv ${virtualenv_name} "${paths}" )
+  else
+    virtualenv=${PYTHON_PATH}/${virtualenv_name}
+  fi
+
+  if [[ -n ${OPT_RESET} ]]; then
+    if [[ -d ${VENV_PATH} ]]; then
+      cmd /bin/rm -rf ${VENV_PATH}
+    fi
+  fi
+
+  if ! [[ -d ${VENV_PATH} ]]; then
+    cmd ${virtualenv} ${VENV_PATH}
+    cmd ${VENV_PATH}/bin/${python_name} --version
+    cmd ${VENV_PATH}/bin/pip install --upgrade pip
+
+    if [[ -f requirements.txt ]]; then
+      cmd ${VENV_PATH}/bin/pip install -r requirements.txt
+    fi
+  fi
+
+  source ${VENV_PATH}/bin/activate && "$@"
+}
+
+export BASE=$(readlink -f $(dirname $0)/..)
 
 set -eo pipefail
 
-MYSELF=$0
-BASE=$(readlink -f $(dirname ${MYSELF})/..)
+myopts=$(getopt --options i:rv:h --longoptions install-path:,reset,version:,help -- "$@" ) || usage
 
+eval set -- "${myopts}"
 
-set_virtualenv_default() {
-  local venv_bin=$1
-  local path
-  for path in ${VIRTUALENV_PATHS}; do
-    if [[ -x ${path} ]]; then
-      VIRTUALENV=$(dirname ${path})/${venv_bin}
-      [[ -x ${VIRTUALENV} ]] && break
-    fi
-  done
-}
-
-[[ -z ${VIRTUALENV} ]] && set_virtualenv_default
-
-venv=${VENV_DIR:-${BASE}/.venv}
-
-if [[ ${1:-""} == '-r' || ${1:-""} == '--reset' ]]; then
-  shift # pop the -r or --reset off the argv variable $@
-
-  if [[ -d ${venv} ]]; then
-    echo
-    echo /bin/rm -rf ${venv}
-         /bin/rm -rf ${venv}
-  fi
-fi
-
-if [[ $1 == '-2' ]]; then
+while true; do
+  case $1 in
+    -h|--help) usage ;;
+    -i|--install-path) OPT_VENV_PATH=$2; shift 2 ;;
+    -r|--reset) OPT_RESET="true"; shift ;;
+    -v|--version) OPT_PYTHON_VERSION=$2; shift 2 ;;
+    --) shift; break ;;
+    *) break ;;
+  esac
   shift
-  VIRTUALENV_PATHS="
-    /opt/hii/python/2.7.13/bin/python2.7
-    /shares/hii/sw/python/2.7.13/bin/python2.7
-    /usr/local/bin/python2.7
-    /usr/bin/python2.7
-  "
-  set_virtualenv_default virtualenv
-else
-  VIRTUALENV_PATHS="
-    /opt/hii/python/3.5.3/bin/python3.5
-    /opt/hii/python-3.5.3/bin/python3.5
-    /shares/hii/sw/python/3.5.3/bin/python3.5
-    /usr/local/bin/python3.5
-    /usr/bin/python3.5
-  "
-  set_virtualenv_default pyvenv
-fi
-
-
-if [[ ! -d ${venv} ]]; then
-  echo
-  echo ${VIRTUALENV} ${venv}
-       ${VIRTUALENV} ${venv}
-
-  echo
-  echo ${venv}/bin/pip install --upgrade pip
-       ${venv}/bin/pip install --upgrade pip
-
-  if [[ -f ${BASE}/requirements.txt ]]; then
-    echo
-    echo ${venv}/bin/pip install -r ${BASE}/requirements.txt
-         ${venv}/bin/pip install -r ${BASE}/requirements.txt
-  fi
-fi
+done
 
 if [[ $# -lt 1 ]]; then
-  echo
-  echo "Usage: ${MYSELF} [-r|--reset] bash|eval|ARGS..." 2>&1
-  echo
-  exit 1
+  usage
 fi
 
-if [[ $1 == 'bash' ]]; then
-  bash --init-file <(echo "[[ -f $HOME/.bash_profile ]] && source $HOME/.bash_profile; source ${venv}/bin/activate;")
-elif [[ $1 == 'eval' ]]; then
-  echo "source ${venv}/bin/activate"
-else
-  source ${venv}/bin/activate
-  "$@"
-fi
+PYTHON_VERSION=${OPT_PYTHON_VERSION:-3}
+
+case ${PYTHON_VERSION} in
+  2) VENV_PATH=${OPT_VENV_PATH:-.venv2} ;;
+  3) VENV_PATH=${OPT_VENV_PATH:-.venv3} ;;
+esac
+
+case ${PYTHON_VERSION} in
+  2) run_python 2 "${PYTHON_2_PATHS}" "$@" ;;
+  3) run_python 3 "${PYTHON_3_PATHS}" "$@" ;;
+  *) echo "$(basename $0): Unsupported Python Version: '${PYTHON_VERSION}'" 1>&2; exit 1;;
+esac
